function [u, v, w] = wake (x, y, z, vortic, qw, it, jb)

    % calculates semi wake induced velocity at point (x,y,z) at t = it*dt
    % in the inertial reference frame

    u = 0;
    v = 0;
    w = 0;
    i1 = it - 1; 

    for i = 1:i1 %1

        for j = 1:jb %1
            vortek = vortic(i, j); 
            [u1, v1, w1] = vortex(x, y, z, ...
                qw(i, j, 1), qw(i, j, 2), qw(i, j, 3), ...
                qw(i + 1, j, 1), qw(i + 1, j, 2), qw(i + 1, j, 3), ...
                vortek); 
            [u2, v2, w2] = vortex(x, y, z, ...
                qw(i + 1, j, 1), qw(i + 1, j, 2), qw(i + 1, j, 3), ...
                qw(i + 1, j + 1, 1), qw(i + 1, j + 1, 2), qw(i + 1, j + 1, 3), ...
                vortek);
            [u3, v3, w3] = vortex(x, y, z, ...
                qw(i + 1, j + 1, 1), qw(i + 1, j + 1, 2), qw(i + 1, j + 1, 3), ...
                qw(i, j + 1, 1), qw(i, j + 1, 2), qw(i, j + 1, 3), ...
                vortek);
            [u4, v4, w4] = vortex(x, y, z, ...
                qw(i, j + 1, 1), qw(i, j + 1, 2), qw(i, j + 1, 3), ...
                qw(i, j, 1), qw(i, j, 2), qw(i, j, 3), ...
                vortek);
            u = u + u1 + u2 + u3 + u4;
            v = v + v1 + v2 + v3 + v4;
            w = w + w1 + w2 + w3 + w4;
        end %1

    end %1

end
